version: '3.8'

services:
  ubuntu:
    platform: linux/amd64
    build:
      context: .
      args:
        username: ${USERNAME}
        password: ${PASSWORD}
    image: nicholasadamou/ubuntu-xfce4:latest
    container_name: ubuntu-xfce4
    ports:
      - "6080:6080"
      - "5999:5999"
      - "7776:22"
    volumes:
      - ./:/code